import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Reveal } from "../components/Reveal";
import { startAudit } from "../lib/api";
import styles from "./Overview.module.css";

export function Overview() {
  const navigate = useNavigate();
  const [url, setUrl] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);

    let target = url.trim();
    if (target && !/^https?:\/\//i.test(target)) {
      target = `https://${target}`;
    }
    if (!target) {
      setError("Enter a URL first.");
      return;
    }

    setSubmitting(true);
    try {
      const { jobId } = await startAudit(target, 8, 12);
      navigate(`/results?job=${jobId}`);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Couldn't start the audit — is the local API server running (uvicorn server:app --port 8000)?",
      );
      setSubmitting(false);
    }
  }

  return (
    <main>
      <section className={styles.hero}>
        <div className={`container ${styles.heroInner}`}>
          <span className={`mono ${styles.eyebrow}`}>
            provenance &amp; disclosure compliance audit
          </span>
          <h1 className={styles.heroTitle}>
            The law assumes AI disclosure marks survive.
            <br />
            <span className={styles.heroAccent}>Test that on any site.</span>
          </h1>
          <p className={styles.heroSub}>
            EU AI Act Article 50(2) and California SB 942 both require
            AI-generated images to carry machine-readable disclosure — and
            for that disclosure to be robust, not incidental. Enter a
            company's URL below to scrape it, triage which images are
            likely AI-generated, and test whether their disclosure signals
            survive a screenshot, a recompress, a crop, a resize.
          </p>

          <form className={styles.form} onSubmit={handleSubmit}>
            <input
              type="text"
              className={styles.input}
              placeholder="example-company.com"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              disabled={submitting}
            />
            <button
              type="submit"
              className={styles.primaryButton}
              disabled={submitting}
            >
              {submitting ? "Starting…" : "Run audit ↗"}
            </button>
          </form>
          {error && <p className={styles.error}>{error}</p>}
          <p className={styles.formHint}>
            Runs a small crawl (8 pages, 12 images) against the local API
            server — takes a few minutes since each flagged image gets a
            real DIRE + SynthID + C2PA check.
          </p>

          <div className={styles.heroActions}>
            <Link to="/results" className={styles.secondaryButton}>
              See an example run ↗
            </Link>
            <Link to="/info" className={styles.secondaryButton}>
              How it works
            </Link>
          </div>
        </div>
      </section>

      <section className={styles.section}>
        <div className="container">
          <Reveal>
            <span className={`mono ${styles.sectionLabel}`}>
              first findings
            </span>
            <h2 className={styles.sectionTitle}>
              What we found auditing elevenlabs.io
            </h2>
          </Reveal>
          <div className={styles.statGrid}>
            <Reveal className={styles.statCard}>
              <span className={styles.statNumber}>0 / 15</span>
              <p>scraped images carried a C2PA manifest</p>
            </Reveal>
            <Reveal className={styles.statCard}>
              <span className={styles.statNumber}>13 / 15</span>
              <p>flagged as likely AI-generated by the triage gate</p>
            </Reveal>
            <Reveal className={styles.statCard}>
              <span className={styles.statNumber}>~83%</span>
              <p>
                of images with a detected watermark lost that signal after
                one basic edit
              </p>
            </Reveal>
          </div>
          <Reveal className={styles.caveat}>
            <p>
              <strong>Read this carefully before citing it:</strong> the
              watermark check is an unofficial, third-party estimate
              trained only on GPT-Image-2 — not Google's own SynthID
              verifier, and unproven on other generators' output. Treat
              these numbers as evidence the pipeline works, not as a
              confirmed claim about any one company.{" "}
              <Link to="/results">See the full per-image breakdown →</Link>
            </p>
          </Reveal>
        </div>
      </section>
    </main>
  );
}
